### PR TITLE
bobs test version with CAT PTT and 700C auto-record

### PR DESCRIPTION
**Pull request by bobwis**
1. Support Hamlib based CAT of PTT
1. Support 700C.  This mode doesn't have a text channel so we cannot Tx based on the trigger string.  However we can still record a file when we get sync which is quite useful.

### CODE REVIEW

**Comment by drowe67** [comment]
thanks @bobwis looks good :+1: 

Looks like the [Travis automated build and test](https://travis-ci.com/github/drowe67/freebeacon/builds/162920538) is failing, we probably need to tell Travis and cmake to include the hamlib stuff.   I'll take a look into that.

**Comment by drowe67** [comment]
@bobwis can you pls give me [permision to modify the code in your PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?  I'm tweaking ```CMakeLists``` and ```.travis.yml``` to get it building OK, and would like to push the changes back to this PR.

**Comment by drowe67** [comment]
@bobwis OK I've pushed a few changes, please try them out and make sure Hamlib still works OK for you.  Look like [Travis is happy](https://travis-ci.com/github/drowe67/freebeacon/builds/163127334) now :smile:

**Comment by bobwis** [comment]
Changed #include rig.h path. My editor auto-changed redundant whitespace.
Tests done:-
Tx and Rx in 1600, 700D and 700C - all good.
Auto-record okay in 700C, still waits for trigger word in 700D

**Comment by drowe67** [comment]
@bobwis that's great well done - I'll go ahead and merge now :+1:

**Pull request merged**
